spring.application.name=Assignment1
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
openai.transcription-url=https://api.openai.com/v1/audio/transcriptions
openai.transcription-model=gpt-4o-mini-transcribe
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
